### ISSUE TITLE
英文版支持

### ISSUE THREAD

**Issue by FunnyWolf** [ffffffff0x/f8x#10]
项目后续是否会支持英文?

**Comment by No-Github** [comment]
shell 脚本做语言切换比较麻烦，我后面直接全改成英文版吧，最近太忙，十一假期把英文版肝出来

**Comment by FunnyWolf** [comment]
> shell 脚本做语言切换比较麻烦，我后面直接全改成英文版吧，最近太忙，十一假期把英文版肝出来

恩,觉得切换也没有必要,可以直接做一个f8x_en这种,单独一个readme

**Comment by No-Github** [comment]
已在 1.5.6 版本改为 英文输出
