### ISSUE TITLE
Unknown version

### ISSUE THREAD

**Issue by FunnyWolf** [ffffffff0x/f8x#13]
使用vultr的vps安装时,报错如下: 

 _______   ___   ___   ___ 
 |   ____| / _ \  \  \ /  / 
 |  |__   | (_) |  \  V  / 
 |   __|   > _ <    >   < 
 |  |     | (_) |  /  .  \ 
 |__|      \___/  /__/ \__\ 

13:05:24 [ERROR] - Unknown version

root@vultr:~#

**Comment by No-Github** [comment]
应该是没匹配到发行版

请提供以下语句的输出
```
cat /etc/*-release
```

**Comment by FunnyWolf** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

**Comment by No-Github** [comment]
哦，新的 21.10 版，马上就加上去

**Comment by No-Github** [comment]
1.5.8 Dev(Beta3) 上测试完毕了,兼容 21.10 的

**Comment by No-Github** [comment]
![image](https://user-images.githubusercontent.com/18167071/140752219-5a683183-cc7b-4234-9927-db41545fb22a.png)

**Comment by FunnyWolf** [comment]
好的
