### ISSUE TITLE
能否支持python3不同版本的安装

### ISSUE THREAD

**Issue by S1xHcL** [ffffffff0x/f8x#14]
使用f8x安装环境为3.6.8，但有些工具要求环境为python3.7以上，例如dirsearch，能否支持指定python3不同版本环境安装

![1](https://user-images.githubusercontent.com/47764705/140895674-24dc887c-e058-43cf-925e-688ddf6b78a6.png)

**Comment by No-Github** [comment]
确实是个问题，我研究下
下个大版本加入

**Comment by No-Github** [comment]
目前在 1.5.8 Dev(Beta6) 版本中添加了如下选项:
* -py3.7
![image](https://user-images.githubusercontent.com/18167071/141392822-e0df3939-e270-4948-8632-02d5b678f944.png)

* -py3.8

![image](https://user-images.githubusercontent.com/18167071/141392849-1e4aa668-a51d-42f1-b9e4-bfe3cb3d126c.png)


* -py3.9
![image](https://user-images.githubusercontent.com/18167071/141392885-320ace5e-11d1-4060-9038-0b34ded0cca1.png)

通过源码编译安装,多个操作系统版本应该是都支持的
第一个选项是询问是否走代理,这里如果是国内vps或虚拟机就 y，走代理，如果是国外vps就直接回车
第二个选项是判断到了 python3 已经安装，是否继续安装 ，默认是 No, 确认版本无误就按 y 即可

**Comment by S1xHcL** [comment]
牛！
