### ISSUE TITLE
遇到docker-compose安装不成功及手动安装过程

### ISSUE THREAD

**Issue by sv3nbeast** [ffffffff0x/f8x#16]
- 安装docker-compose时遇到报错
  Could not find a version that satisfies the requirement docker[ssh]>=5 (from docker-compose) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0, 3.2.1, 3.3.0, 3.4.0, 3.4.1, 3.5.0, 3.5.1, 3.6.0, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.2.0, 4.2.1, 4.2.2, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4)
No matching distribution found for docker[ssh]>=5 (from docker-compose)
- 手动使用命令pip3 install --upgrade pip
- 手动使用命令pip3 --trusted-host pypi.python.org install -U docker-compose
- 安装docker-compose成功

感谢师傅提供的工具节省了很多时间

**Comment by sv3nbeast** [comment]
Linux ls_KNjsIBKZ 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux

**Comment by No-Github** [comment]
看上去是机器 pip3 没有更新造成的，我在安装前加个 pip3 install --upgrade pip 命令吧，感谢师傅提供的详细issue信息和解决方案

**Comment by No-Github** [comment]
如果没有其他问题，这个 issue 我就先关闭了，多谢师傅对 f8x 的支持
