### ISSUE TITLE
CS has been damaged

### ISSUE THREAD

**Issue by k646685609** [ffffffff0x/f8x#17]
CS decompression failed and the file is damaged

**Comment by No-Github** [comment]
我这边测试了是正常解压的 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/18167071/161536567-95c5dcac-303e-4756-b1e0-6c25c01623e2.png">

运行也没有问题
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/18167071/161536819-63e36fbf-bec7-48aa-a174-e80f688437fb.png">

能提供更加详细些的信息吗，或者您可以运行下面的命令来进行测试
```
cd /tmp
wget -O CobaltStrike4.3.zip https://raw.githubusercontent.com/No-Github/Archive/master/CS/CobaltStrike4.3.zip
unzip CobaltStrike4.3.zip
```

**Comment by k646685609** [comment]
It could be network fluctuation
