### ISSUE TITLE
安装vol3遇到问题

### ISSUE THREAD

**Issue by Shellc0d** [ffffffff0x/f8x#18]
![image](https://user-images.githubusercontent.com/53160265/161748802-ca6df77f-650e-4c93-8256-80232f3d9daa.png)
安装vol3后使用遇到问题

**Comment by No-Github** [comment]
vol3 没有 imageinfo 命令，vol2 里才有
```
cd /pentest/volatility3
python3 vol.py -f lab0.raw layerwriter
```
如果你需要 vol3 的详细使用帮助,可以参考我另一个笔记项目中的内容 https://github.com/ffffffff0x/1earn/blob/master/1earn/Security/%E5%AE%89%E5%85%A8%E5%B7%A5%E5%85%B7/Volatility.md#volatility3

**Comment by Shellc0d** [comment]
> vol3 没有 imageinfo 命令，vol2 里才有
> 
> ```
> cd /pentest/volatility3
> python3 vol.py -f lab0.raw layerwriter
> ```
> 
> 如果你需要 vol3 的详细使用帮助,可以参考我另一个笔记项目中的内容 https://github.com/ffffffff0x/1earn/blob/master/1earn/Security/%E5%AE%89%E5%85%A8%E5%B7%A5%E5%85%B7/Volatility.md#volatility3

感谢师傅！

**Comment by No-Github** [comment]
没事，这个 issue 我就先关闭了，如果你有其他安全方面的问题，但与 f8x 无关，可以在 https://github.com/ffffffff0x/1earn/issues 进行提问。
