### ISSUE TITLE
一键安装VIPER时遇到的问题

### ISSUE THREAD

**Issue by wxx0105** [ffffffff0x/f8x#19]
安装的时候会问我proxy，就是这个弹出来proxy的配置，我不懂如何是好啊，哪里都没找到说明，故来此问问，上图
![8Q(1 6`9 V$60P~S96EE0XG](https://user-images.githubusercontent.com/71886755/164725243-66da45cb-ef85-4288-9d03-74588b470082.png)

**Comment by No-Github** [comment]
如果选择走 proxy 就是自动安装 Proxychains-ng,弹出来的页面是 vim 打开 /etc/proxychains.conf 的页面,配置代理就行
如果选择不走 proxy ,就是先检测是否已安装 docker ,没有安装会自动装 docker,这里报错应该是在运行以下这条命令的时候出错了
```
proxychains4 curl -o /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/centos/docker-ce.repo
```

应该是你选择了走代理，又没有配置 /etc/proxychains.conf 导致通过 proxychains4 下载失败,所以后面都报错

解决方法
1. 确保你linux当前的网络环境是否可以直接访问google,可以就不用走代理，不可以就请自行配置 /etc/proxychains.conf 文件,然后走 proxy 即可

**Comment by wxx0105** [comment]
了解，栓q，刚刚也发现是未配置问题❤

**Comment by No-Github** [comment]
好的，这个issue就先关闭了
