### ISSUE TITLE
Viper安装

### ISSUE THREAD

**Issue by FunnyWolf** [ffffffff0x/f8x#2]
viper应该安装不上,因为在docker-compose.yml中写死了/root/viper,所以挂载不上/tmp/viper

**Comment by No-Github** [comment]
明白了，需要在 /root/viper 目录下进行 docker-compose up -d，这就改

**Comment by FunnyWolf** [comment]
> 明白了，需要在 /root/viper 目录下进行 docker-compose up -d，这就改

或者直接改docker-compose.yml中的/root/viper目录或者让用户自己输入目录,这样更灵活
另外能否加一个增加虚拟内存的功能,一般vps内存都比较小,运行多个工具内存可能爆掉

**Comment by No-Github** [comment]
好的，我放到TODO计划里，这几天做出来

**Comment by No-Github** [comment]
已在 v1.4.5 中添加,效果如下
![Snipaste_2021-02-28_01-42-49](https://user-images.githubusercontent.com/18167071/109416587-1cfc1700-79fa-11eb-9935-81a9e966671d.png)
