### ISSUE TITLE
安装ARL的一个小问题

### ISSUE THREAD

**Issue by skr-rks** [ffffffff0x/f8x#20]
![image](https://user-images.githubusercontent.com/57212526/167824417-b35096df-806a-4cf6-a5be-1cc0998ca213.png)
安装完成后，在pentest这个目录下没有arl目录。当然可以docker run自己构建，哈哈哈

**Comment by No-Github** [comment]
应该是在执行 `git clone --depth 1 https://github.com/TophantTechnology/ARL` 的时候出错了，所以导致没有这个目录，我后面优化下这个错误输出，不然遇到这种情况确实比较懵逼，多些师傅的反馈
