### ISSUE TITLE
建议添加CDK

### ISSUE THREAD

**Issue by okoling** [ffffffff0x/f8x#23]
https://github.com/cdk-team/CDK

**Comment by No-Github** [comment]
ok,下个更新就加上去

**Comment by okoling** [comment]
> ok,下个更新就加上去

再加个 yakit就更好了~

**Comment by No-Github** [comment]
已添加 cdk 工具在 `-k` 选项中
已添加 yakit 工具在 `-yakit` 选项中
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/18167071/169468443-41aa208a-9c26-417d-ba41-b6769b0e5bc6.png">

**Comment by No-Github** [comment]
如果没有其他问题，这个issue我就先关闭了，后面师傅有其他好的意见或不错的工具推荐可以在提哈

**Comment by okoling** [comment]
nice，很完美~
