### ISSUE TITLE
建议添加MSF、CS

### ISSUE THREAD

**Issue by wowtalon** [ffffffff0x/f8x#24]

**Comment by No-Github** [comment]
你好，目前现有的选项里支持这2个工具哦
-k 选项中安装 msf 框架
-cs 选项会安装 CobaltStrike 4.3
师傅可以自己测试一下,如果还有其他的问题也欢迎提出

**Comment by No-Github** [comment]
如果没有其他问题，这个issue我就先关闭了，后面师傅有其他好的意见或不错的工具推荐可以在提哈
