### ISSUE TITLE
申请安装列表中增加一个工具

### ISSUE THREAD

**Issue by sv3nbeast** [ffffffff0x/f8x#26]
请问师傅可以添加一个这个工具的安装吗
- pupy: https://github.com/n1nj4sec/pupy

**Comment by No-Github** [comment]
pupy选项已添加,使用思路是起pupy容器，按需求映射端口

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/18167071/183359384-95791ac1-d008-4033-9fdd-24c20f213194.png">

使用的时候直接 ssh 进pupy容器
<img width="1890" alt="image" src="https://user-images.githubusercontent.com/18167071/183359594-2bc39f52-3557-400f-b9fd-667ff5af5c79.png">


师傅有需求和建议可以再提

**Comment by sv3nbeast** [comment]
上面还有个
docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

**Comment by sv3nbeast** [comment]
后续进行了一些步骤
利用f8x重新安装了docker   bash  f8x -docker
docker删除了已下载的容器 docker rm xxxxxx
bash f8x -pupy重新安装pupy，报错消失，pupy运行成功，具体是什么解决也不太清楚

**Comment by No-Github** [comment]
很遗憾，我这边测试了几次新开通Ubuntu22.04服务器，均未复现这个错误
搜索了下相关issue，发现多个解决方案 https://github.com/docker/for-linux/issues/219

- 手动挂载 cgroup
```
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

- 安装 cgroup-tools
```
sudo apt-get update
sudo apt-get -y install cgroup-tools
```

下次师傅再遇到这个问题可以试下这个issue里提到的2种解决方案
