### ISSUE TITLE
增加工具

### ISSUE THREAD

**Issue by toecesws** [ffffffff0x/f8x#27]
wpscan
https://github.com/wpscanteam/wpscan
MoreFind
https://github.com/mstxq17/MoreFind
都是很不错的工具~

**Comment by toecesws** [comment]
刚发现cme已经有了~所以关闭issue了，用回同一个吧~

**Comment by No-Github** [comment]
ok,下个更新就加上去

**Comment by No-Github** [comment]
已添加
MorkFind 在 `-k` 选项中进行安装
wpscan 使用 `-wpscan` 选项进行安装
