### ISSUE TITLE
f8x安装的docker版本与ARL参数不匹配

### ISSUE THREAD

**Issue by 14569632587** [ffffffff0x/f8x#28]
f8x安装的docker版本为1.8，是不是与ARL配置文件不匹配   开发大哥们看下

**Comment by 14569632587** [comment]
好像是我的系统版本太久了

**Comment by No-Github** [comment]
刚刚更新了一下，师傅在运行下看看呢，如果还是不行，麻烦贴一下报错截图方便我排查下是啥问题

**Comment by No-Github** [comment]
如果没有其他问题，这个issue我就先关闭了，后面师傅遇到其他问题可以再反馈。
