### ISSUE TITLE
【功能建议】go安装指定版本

### ISSUE THREAD

**Issue by soapffz** [ffffffff0x/f8x#29]
默认安装的似乎是1.17版本

建议默认为1.18版本，增加额外选项安装最新版本

**Comment by No-Github** [comment]
ok,下个更新就加上去

**Comment by No-Github** [comment]
已更新,使用 `-go` 选项更新即可
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/18167071/192224525-066e656d-2a85-4bbb-8473-7bd66b044eb0.png">

**Comment by No-Github** [comment]
参考上面的代码，我修改了下
<img width="838" alt="image" src="https://user-images.githubusercontent.com/18167071/192241426-53f571c6-0ffa-4a71-ae7f-21a40beea9cb.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/18167071/192241781-6843807b-56bc-4a7b-94be-67ff8ca324af.png">

师傅在看下，还有啥需求不

**Comment by soapffz** [comment]
同理我相信其他的软件需要制定版本的时候也有类似需求，需要直接默认安装，而不是用户输入，当然在程序中维护每个软件的版本也不是易事，我也不知道有没有成熟的解决方案。。

**Comment by No-Github** [comment]
关于第一点非交互式的场景优化，我看了下，其实大部分交互选项是关于代理、镜像源功能的，这个只要不运行-p就可以了
而师傅所说的安装 go 最新版,这里我加了几行，只需要在/tmp 创建个空的 IS_CI 文件，这里就跳过用户输入
<img width="894" alt="image" src="https://user-images.githubusercontent.com/18167071/192423248-fa06136e-ad37-4787-b661-ac153724f80d.png">

第二点，指定版本，这里我了解到通过 . ./test.sh 这样同等进程运行可以修改当前shell环境变量，那么我这里对 f8x_version.sh 这个文件做个判断，当有这个文件时，会加载这个文件中的内容，也就是覆盖f8x的变量值，这样师傅只需要对f8x_version.sh 文件做修改或定制，即可做到安装指定版本
<img width="280" alt="image" src="https://user-images.githubusercontent.com/18167071/192423814-b8292c15-4c56-49ed-a255-08c5288424d4.png">

**Comment by soapffz** [comment]
touch /tmp/IS_CI 文件之后，好像没能成功进行判断，装完还是1.17

暂时以[这种方式](https://github.com/soapffz/myman/blob/bd8a3a03fc0cce42f423cdb07e001a2529df7d11/xxl-job-executor/Dockerfile#L58)实现了，感谢支撑

关闭issue
