### ISSUE TITLE
安装viper的问题

### ISSUE THREAD

**Issue by dupengshenyang** [ffffffff0x/f8x#30]
两个系统一个是centos stream 9 还有一个是centos8 都出现了
![image](https://user-images.githubusercontent.com/8084847/194732235-ddb85177-e9cd-4f94-a91f-539f439f27a0.png)
![image](https://user-images.githubusercontent.com/8084847/194732240-5ae41bbc-f58a-4cc5-9e65-eeef2f6d1fca.png)
![image](https://user-images.githubusercontent.com/8084847/194732248-1cd1abee-36dd-44e3-8c97-d47276e9be54.png)

yum erase podman buildah卸载podaman 
之后再安装docker CE：yum install -y docker-ce docker-ce-cli containerd.io  然后执行f8x -viper解决问题

**Comment by No-Github** [comment]
排查了下，问题原因是 docker 服务没有启动，手动解决方案 : 运行 `service docker start` 即可

**Comment by No-Github** [comment]
后面加上自动开docker服务，这个问题在新版将自动解决

**Comment by No-Github** [comment]
如果没有其他问题，这个issue我就先关闭了，后面师傅遇到其他问题可以再反馈。
