### ISSUE TITLE
remove 

### ISSUE THREAD

**Issue by sec13b** [ffffffff0x/f8x#34]
how i remove a image installed with  f8x

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curl -o f8x https://f8x.io/   # wget -O f8x https://f8x.io/
bash f8x -viper
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by No-Github** [comment]
# stop viper
cd /root/VIPER && docker-compose stop

# rm viper docker images
docker image ls
docker image rm viper:latest
