### ISSUE TITLE
docker-compose已经废弃,最新版是docker compose

### ISSUE THREAD

**Issue by FunnyWolf** [ffffffff0x/f8x#35]
docker-compose官方已经停止维护,当前最新版的docker已经通过plugin的方式支持docker compose命令

**Comment by No-Github** [comment]
感谢提醒,新版本更换了安装方案
<img width="1303" alt="image" src="https://github.com/ffffffff0x/f8x/assets/18167071/bc43984c-bd9f-44e6-b1dd-4f0d58c604b4">

**Comment by FunnyWolf** [comment]
![image](https://github.com/ffffffff0x/f8x/assets/17685281/16948947-baf0-4369-89ba-5722d508ea06)

**Comment by No-Github** [comment]
原来调用的命令忘记修改了,已经更新https://github.com/ffffffff0x/f8x/commit/e16f3064b88a802e533353174bff5620c7b0036f
