### ISSUE TITLE
centos7 docker compose安装问题

### ISSUE THREAD

**Issue by xizyy** [ffffffff0x/f8x#37]
用f8x安装docker会安装旧版的docker
![image](https://github.com/ffffffff0x/f8x/assets/44395437/e013c8ab-9aa9-48c3-8eb5-92ce44f3eee1)
导致无法使用docker compose
![image](https://github.com/ffffffff0x/f8x/assets/44395437/2b9831db-d90b-4a3f-9007-ddd8eb25decb)

**Comment by No-Github** [comment]
目前可以先使用旧版 docker-compose 工具拉起镜像

安装旧版的问题应该是包管理工具未更新的缘故,能否提供下系统发行版的具体信息呢以协助我排查下问题呢?

**Comment by No-Github** [comment]
已更新
https://github.com/ffffffff0x/f8x/commit/dfdc08f21a158013aa5b0f1c70b2d5b148384ca5#diff-326059e4379110ac01ce6f724ddb41d2f0a38d5da12ca642e9fc1fbb811232feR2653
