### ISSUE TITLE
[BUG] kali安装viper报错

### ISSUE THREAD

**Issue by FunnyWolf** [ffffffff0x/f8x#38]
bash f8x -viper
![263581828-bf2f385e-bb2d-4ce3-b498-904c9d83a123](https://github.com/ffffffff0x/f8x/assets/17685281/e9a3f567-2ecd-48f5-b35d-ca86b48ab1bf)

**Comment by FunnyWolf** [comment]
@No-Github

**Comment by No-Github** [comment]
已更新
