### ISSUE TITLE
debian12无法使用吗

### ISSUE THREAD

**Issue by yz1639** [ffffffff0x/f8x#39]
![image](https://github.com/ffffffff0x/f8x/assets/44149984/02763a50-5c0d-4834-b678-24a92bf80b35)

![image](https://github.com/ffffffff0x/f8x/assets/44149984/65a3bb44-e1cf-46d7-808b-34d9366fa8c1)

能否适配下debian12 🙏

**Comment by No-Github** [comment]
感谢反馈，已经适配
