### ISSUE TITLE
给作者提一个小需求

### ISSUE THREAD

**Issue by RedTeamWing** [ffffffff0x/f8x#4]
https://github.com/Thrimbda/shell-set-up

可以加入一下支持zsh的安装自动化配置插件。

**Comment by No-Github** [comment]
好的，近期适配

**Comment by No-Github** [comment]
已在 v1.4.8 中添加,效果如下
![Snipaste_2021-03-28_11-08-20](https://user-images.githubusercontent.com/18167071/112746055-24094b80-8fdf-11eb-9a4e-bed7c0e96cbd.png)
![Snipaste_2021-03-28_11-08-49](https://user-images.githubusercontent.com/18167071/112746056-24a1e200-8fdf-11eb-8632-1b7b80854cb1.png)
