### ISSUE TITLE
组件更新

### ISSUE THREAD

**Issue by s1g0day** [ffffffff0x/f8x#40]
metasploit安装后提示postgresql selected, no connection

这是因为没有配置postgresql的问题。

期待作者后续能改进一下，既然自动装msf了，那依赖的数据库也不能落下了

**Comment by No-Github** [comment]
多谢师傅反馈，之前没注意，我看看这个问题

**Comment by No-Github** [comment]
我看了下，pgsql 是安装了的，问题出在 数据库服务 没有开启

师傅可以看下这个
https://blog.csdn.net/zhoufeisi/article/details/105232429

我自己试了下
```
msfdb init
msfdb start
```

然后重新 msfconsole 里面 db_status 就正常了

**Comment by No-Github** [comment]
安装完 msf自动开 pgsql 这个我其实不是很希望在f8x中去做

因为 Pentest_Metasploit_Install 这个函数是在 -k 的选项里默认跑的，可能很多师傅会图方便， -k 直接一把梭安装，这里如果开 pgsql 可能很多师傅并不清楚会造成一定的误解，并且如果不使用msf，也会造成不必要的资源占用

针对这个 issue，我想的解决方案是在安装完毕后会进行提示，让使用者自行去 复制粘贴这个 命令,其实也就是 几秒钟的事

**Comment by No-Github** [comment]
如果师傅没有其他问题，这个 issue 我这周就关闭了

**Comment by s1g0day** [comment]
哈哈，感谢师傅的答疑，

**Comment by s1g0day** [comment]
我试了下，确实是这样的，还是msf用的少了[苦笑]
