### ISSUE TITLE
awvs更新

### ISSUE THREAD

**Issue by s1g0day** [ffffffff0x/f8x#41]
首先热评: 好用！！！

今天试用了./f8x -awvs14

启动后提示：

![image](https://github.com/ffffffff0x/f8x/assets/31206471/80cf229a-6ec2-4da2-b07a-880c3599e42c)

并且这种状态下，登录后需要`Activate License`

看下[SECFA / awvs](https://hub.docker.com/r/secfa/awvs)的更新

```
最新更新：20240227
更新最新版本（24.1.240111130）
自 15.4.230222085 起需要新的启动命令参数 --cap-add LINUX_IMMUTABLE
自 23.11.231123131 Beta 通道开始不需要 LINUX_IMMUTABLE： docker run -it -d -p 13443:3443 secfa/docker-awvs:beta
```

可以修改为

`docker run -it -d -p 13443:3443 secfa/docker-awvs:beta`
或
`docker run -it -d -p 13443:3443 --cap-add LINUX_IMMUTABLE secfa/docker-awvs`

这两个标签拉取的都是最新版本。

**Comment by No-Github** [comment]
感谢师傅反馈，已经更新

https://github.com/ffffffff0x/f8x/commit/361e26202cb3583ec628400bf2c5975e9d2e80e4
