### ISSUE TITLE
pupy一些问题

### ISSUE THREAD

**Issue by okoling** [ffffffff0x/f8x#42]
1. 以docker这种情况安装，会进入终端类似tmux这种终端不方便看长文字？（有解决方法吗？
2. 可以在安装时候自定义多映射几个端口吗？

**Comment by No-Github** [comment]
第一个问题： tmux 形式的交互方式，这个是 pupy 作者的 docker 容器本身交互使用就是这样，确实麻烦，这个还是把 tmux 快捷键用熟练把，如果不用 docker 安装，也可以尝试自行下载源码安装
第二个问题： 自定义多映射几个端口，这个当然可以，我后面添加几个映射端口

其实目前 c2 还是有比较多的选择，建议师傅看看 sliver、supershell、Merlin、reverse_ssh 这些 c2 项目，希望可以解决师傅目前的困扰

**Comment by okoling** [comment]
1. 刚学了下tmux搜索功能还可以就是没那么畅快。。目前源码安装比较麻烦各种错误
2. 可以自己配置最好，有时候要转发端口啥的。

用来用去还是pupy用的舒服一点，用其他的总感觉怪怪的

**Comment by No-Github** [comment]
<img width="719" alt="image" src="https://github.com/ffffffff0x/f8x/assets/18167071/55fc6b74-7cdd-4d52-8d51-c7d51ddbac6f">
补充了个自定义端口范围的交互
