### ISSUE TITLE
f8x -msf是不是失效了

### ISSUE THREAD

**Issue by byXewl** [ffffffff0x/f8x#44]
f8x -msf是不是失效了，有代理也安不起

**Comment by No-Github** [comment]
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/ed737122-1a80-4441-9ea9-ba93e4c4b0fe">
<img width="851" alt="image" src="https://github.com/user-attachments/assets/6861c5c9-3a2e-4faa-b544-73a2f4f9fd61">
我在亚马逊开了个机器测试了一下，默认进去 用 -msf 一切正常

师傅麻烦提供下您运行环境的版本
```
uname -a
```

如果方便可以以调试模式运行脚本，查看详细输出日志
```
bash -xv f8x -msf
```
将具体报错的部分贴在 issue 中
