### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by Tgentimc** [ffffffff0x/f8x#6]
1、f8x -nginx命令安装nginx的时候会报错无法安装，apt-get install zlib1g zlib1g.dev，安装这2个依赖在执行就可以了。
2、cs能不能换成4.2或者4.3

**Comment by No-Github** [comment]
好的，近期适配

**Comment by No-Github** [comment]
zlib1g zlib1g.dev 依赖已在 1.5.2 中添加，其他版本的cs，我这几天找下，加进去

**Comment by No-Github** [comment]
cs4.3 在 1.5.3 已支持
