### ISSUE TITLE
首次安装的建议

### ISSUE THREAD

**Issue by FunnyWolf** [ffffffff0x/f8x#7]
f8x在下载有两种选择
- 在github release
- 在 jsdelivr cdn下载
但是这两种下载都太长了,一般也记不住,f8x主脚本一共200多k,能不能部署在类似f8xf8x.xyz这种域名上,使用
```
wget https://f8xf8x.xyz/f8x
```
这种方式下载,这样就不用每次都访问一下github主页了.

**Comment by No-Github** [comment]
好的，等会就买域名👌
