### ISSUE TITLE
能否开源代码以便自行修改。

### ISSUE THREAD

**Issue by scareing** [ffffffff0x/f8x#9]
1. 虽然f8x已经能满足大部分需求，但是部署后的一些细节配置（如 api，去特征），仍需手动配置，希望能开源代码，自行修改和补充

**Comment by No-Github** [comment]
你好，没有搞明白你的需求，f8x 是 bash shell 脚本，我也没有做 shc 混淆,代码都是所见即所得。
因为 Apache License 2.0 的协议，也可以随意做修改和分发，甚至商用都是可以的，请问我还需要开源那一部分呢？

**Comment by scareing** [comment]
不好意思，没.sh后缀，我以为是elf可执行文件

**Comment by No-Github** [comment]
没关系，欢迎提出其他的想法和建议💕
